
spring:
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: 81659017065-gm39pqb2lnem75vcrf8fmsupqv0n8t1h.apps.googleusercontent.com
              client-secret: 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
              scope:
                - email
                - profile
#          provider:
#            google:
#              authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#              token-uri: https://www.googleapis.com/oauth2/v4/token
#              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#              user-name-attribute: sub
  datasource:
    # save the database in the backend folder
    url:  jdbc:sqlite:./backend/src/database/database.db
    driver-class-name: org.sqlite.JDBC
    username: root
    password: root
  sql:
    init:
      mode: always
  main:
    banner-mode: "off"
  #    web-application-type: servlet
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true
      jdbc:
      lob:
        non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: springboot
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
logging:
  level:
    org:
      springframework:
        security: trace
        web: trace
#    com:
#        example:
#            springboot: debug
#    pattern:
#      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"




